name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest ]
        build_type: [ Release ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install deps (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install --formula cmake raylib

      - name: Install deps (Windows)
        if: runner.os == 'Windows'
        run: |
          git clone https://github.com/microsoft/vcpkg.git vcpkg
          cd vcpkg
          git checkout 5b1214315250939257ef5d62ecdcbca18cf4fb1c
          .\bootstrap-vcpkg.bat
          .\vcpkg.exe install raylib:x64-windows-static

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Configure
        run: |
          mkdir -p build
          cmake -B build -S . \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            ${{ runner.os == 'Windows' && '-DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake' || '' }}

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} --parallel

      - name: Strip macOS binary
        if: runner.os == 'macOS'
        run: |
          [ -f build/Release/evogrid ] && strip build/Release/evogrid
          [ -f build/evogrid ]         && strip build/evogrid

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: EvoGrid-${{ matrix.os }}-v${{ github.ref_name }}
          path: |
            build/Release/evogrid*
            build/evogrid*