name: CI

on:
  push:
    branches: [ main ]
    tags:    [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:         [ macos-latest, windows-latest ]
        build_type: [ Release ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install deps (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install --formula cmake raylib

      - name: Build Raylib (Windows)
        if: runner.os == 'Windows'
        run: |
          git clone https://github.com/raysan5/raylib.git raylib_src
          cd raylib_src
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release --parallel
          cmake --install . --prefix "%GITHUB_WORKSPACE%/raylib_install"

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Configure (macOS)
        if: runner.os == 'macOS'
        run: |
          mkdir -p build
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Configure (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir build
          cmake -S . -B build \
            -G "Visual Studio 17 2022" -A x64 \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_PREFIX_PATH="${{ github.workspace }}/raylib_install"

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} --parallel --verbose

      - name: Strip macOS binary
        if: runner.os == 'macOS'
        run: |
          for p in build/Release/evogrid build/evogrid; do
            [ -f "$p" ] && strip "$p"
          done

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: EvoGrid-${{ matrix.os }}-v${{ github.ref_name }}
          path: |
            build/${{ matrix.build_type }}/evogrid*
            build/evogrid*
            build/${{ matrix.build_type }}/evogrid*.exe